---
- name: copy the service file
  copy: src=org.gnu.emacs.plist dest=~/Library/LaunchAgents/org.gnu.emacs.plist
- name: enable the service
  command: launchctl load -w ~/Library/LaunchAgents/org.gnu.emacs.plist
